### PR TITLE
Restore GC functionality, minor housekeeping

### PR DESCRIPTION
**Pull request by aph3rson**
This PR aims to restore the gift card example code, which appears to have been commented out in c02fa41.

In addition, it removes some latent `.pyc`s, which left in by accident in ee6cf55.

### CODE REVIEW

**Comment by samtstern** [comment]
First of all thanks @aph3rson for sending this PR.  I think the gift card stuff was removed on purpose ... @krimchansky do you know about that?

**Comment by aph3rson** [comment]
It looks like it was removed in c02fa41, but there's no explanation why.

I can, however, confirm that it all _works_, and was able to issue gift cards using my issuer ID successfully.

**Comment by krimchansky** [comment]
Thanks for the change, there was not a real reason that I know of on why we had the gift card function disabled.

**Comment by aph3rson** [comment]
Of course! I do note that the committer doesn't appear to have a Github account, so I figured you all would be the best point of contact.

Also, I had a quick S2AP API question - I sent it in via email, and haven't gotten a response. @krimchansky or @samtstern if you're able, could you shoot me an email?

**Comment by samtstern** [comment]
@aph3rson my S2AP knowledge has rusted to the point of uselessness so I will leave this request to @krimchansky or another member of the team.  Hope you get some help!

**Pull request merged**
